version: "3.9"
services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: /Users/milosstanisavljevic/.aws
        target: /root/.aws
  crawler:
    build: ./crawler
    volumes:
      - type: bind
        source: /Users/milosstanisavljevic/.aws
        target: /root/.aws

